name: Deploy StoryBook

on:
  push:
    branches:
      - master
    

jobs:
  build-and-deploy:
    - run-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@3
        with:
          node-version: 16
      
      - name: Install Dependencies
        run: npm ci --legacy-peer-deps
      
      - name: Build StoryBook
        run: npm run deploy-storybook

      - name: Deploy storybook to GitHub Pages
        run: npm run deploy-storybook -- --ci --existing-output-dir=storybook-static
        env:
          GH_TOKEN: ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}